### ISSUE TITLE
BSP 1.0 Issue

### ISSUE THREAD

**Issue by y22ma** [tfoote/ros_ifc6410_guide#3]
The guide recommends using IFC6410 stock BSP 1.0 image, but the image itself is somewhat problematic. For some reasons it seems to fragment the already small eMMC storage into 21 partitions, with the main ubuntu fs sitting on the 13th. 

Would you recommend installing the Linaro builds instead?

**Comment by trainman419** [comment]
The BSP 1.0 _IS_ the Linaro 14.05 build.

You'll have the same number of partitions with either approach; most of them are used for parts of the bootloader and firmware for the various sub-processors (DSPs and things). The Linaro instructions explain the purpose of most of them.

**Comment by tfoote** [comment]
Check here for more info on various partitions: https://wiki.linaro.org/Boards/IFC6410

It does suggest that you can clear out some of those other drives. We strongly recommend leaving them as layed out by Linaro, and use the SD card as we have documented.
