### ISSUE TITLE
Upgrade to BSP 1.3

### ISSUE THREAD

**Issue by tfoote** [tfoote/ros_ifc6410_guide#4]
I've been testing with BSP 1.3 and the uSD card writing issues has been resolved. We can update to use that now in the instructions. 

There are still missing kernel drivers. It looks like we won't be able to avoid telling people to compile their kernel...

**Comment by tfoote** [comment]
FTDI missing: http://mydragonboard.org/community/hw-sw-8064/ftdi-usb-device-on-ifc6410/

**Comment by trainman419** [comment]
I don't think it should be necessary for every user to compile their own kernel; we can do it once and distribute the resulting binaries.

How do you feel about distributing a modified version of the BSP 1.3 image with a custom kernel and modules?

Alternately, we could distribute the kernel (or boot image) and modules by themselves, and have special instructions for how to install them.

**Comment by tfoote** [comment]
It would definitely be better to repackage the BSP, but there's an issue with redistrubuting the firmware.

**Comment by tfoote** [comment]
What would be best would be for us to push upstream to enable more of the kernel modules like most other linux distributions.

**Comment by trainman419** [comment]
Given that it took about a month for the upstream developers for even acknowledge the microSD bug, and several more months before it was fixed, I'm not optimistic about their ability to produce an updated BSP with new drivers in a reasonable amount of time.

**Comment by tfoote** [comment]
most of the networking can be resolved by removing the eth0 entries in the /etc/network/interfaces: http://mydragonboard.org/community/hw-sw-8064/ifc6410-bsp-1-3-does-not-sutdown-eth0-interface-when-ethernet-cable-is-unplugged/#p3074
